
import { getRecipes } from '@/app/actions';
import { RecipeCard } from '@/components/recipe-card';
import { auth } from '@/lib/firebase';

async function getUserId() {
    // This is a simplified way to get the user on the server.
    // In a real-world app, you might use a more robust session management solution.
    // Note: This only works if the server-side environment has access to the user's state.
    // For server components, this can be tricky. A proper solution involves passing tokens
    // or using a library that manages server-side sessions.
    return auth.currentUser?.uid;
}

export default async function RecipesPage() {
  const userId = await getUserId();
  const recipes = await getRecipes(userId);

  return (
    <div className="container mx-auto px-4 py-8 md:py-12">
      <section className="text-center mb-12">
        <h1 className="text-4xl md:text-5xl font-bold font-headline tracking-tight">
          Our Recipe Collection
        </h1>
        <p className="mt-4 text-lg text-muted-foreground max-w-2xl mx-auto">
          Browse through a variety of delicious recipes generated by our community and our AI chef.
        </p>
      </section>

      {recipes.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {recipes.map((recipe) => (
            <RecipeCard key={recipe._id} recipe={recipe} />
          ))}
        </div>
      ) : (
        <div className="text-center py-16">
          <p className="text-muted-foreground text-lg">No recipes found yet. Be the first to generate one!</p>
        </div>
      )}
    </div>
  );
}
